
name: Build Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install npm dependencies
      run: npm install
    
    - name: Run unit tests
      run: npm run test:unit

    - name: Display SoftUni username
      run: echo 'ioannaabadjieva'

  ui_test:
    runs-on: ubuntu-latest
    needs: build_test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install npm dependencies
      run: npm install

    - name: Install Playwright
      run: npx playwright install

    - name: Start the application
      run: npm start &

    - name: Run UI tests
      run: npm run test:ui

  deploy_render:
    runs-on: ubuntu-latest
    needs: ui_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true 